### ISSUE TITLE
Submission Loco Deprl Failing at EvalAI -- No module named 'myosuite'

### ISSUE THREAD

**Issue by YusseffRuiz** [MyoHub/myochallenge_2023eval#8]
Last week submissions worked fine, however, whenever i'm trying to upload a new submission via Submission Loco Deprl, i'm getting the following error in the EvalAI platform:

```
Loading experiment from deprl_baseline/myoLeg_test
Traceback (most recent call last):
  File "agent_loco_deprl.py", line 60, in <module>
    policy = deprl.load(path=foldername, environment=DummyEnv(env_name='myoChallengeChaseTagP1-v0', stub=rc))
  File "/usr/local/lib/python3.8/site-packages/deprl/utils/utils.py", line 40, in load
    exec(header)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'myosuite'

```

I removed the repository and copied again and is still giving the same issue.

In the debug over github with the submission action and the docker it give no errors.

**Comment by YusseffRuiz** [comment]
It solved by itself, nothing was changed. Possibly an issue with the EvalAI platform
